Name "rhvoice"
GenericExecuteSynth "/bin/sh -c 'export PULSE_SERVER=unix:/run/user/1000/pulse/native XDG_RUNTIME_DIR=/run/user/1000; echo \"$DATA\" | RHVoice-test -p slt | paplay'"
GenericCmdDependency "RHVoice-test"
AddVoice "en" "FEMALE1" "slt"
AddVoice "en" "MALE1"   "slt"
DefaultVoice "slt"
