name: Linux

on:
  push:
    branches:
      - 'aviant/V4.2'
      - 'aviant/v5.0'
      - 'Stable*'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**' # Do not trigger for any changes under docs
  pull_request:
    paths:
      - '.github/workflows/linux.yml'
      - '.github/actions/**'
      - 'deploy/linux/**'
      - 'src/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - 'cmake/**'

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash

    env:
      ARTIFACT: QGroundControl-x86_64.AppImage
      PACKAGE: QGroundControl-x86_64
      QT_VERSION: 6.8.3
      # Debug + unit tests on pull requests; Release build on merge / tag.
      BUILD_TYPE: ${{ github.event_name == 'pull_request' && 'Debug' || 'Release' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          fetch-tags: false

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}
        run: |
          git fetch --all --tags -f --depth 1

      - name: Initial Setup
        uses: ./.github/actions/common

      - name: Install Dependencies
        run: |
          chmod a+x ./tools/setup/install-dependencies-debian.sh
          sudo ./tools/setup/install-dependencies-debian.sh

      - name: Install Vulkan
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
          sudo apt update
          sudo apt install vulkan-sdk

      - name: Setup Caching
        uses: ./.github/actions/cache
        with:
          host: linux
          target: linux_gcc_64
          build-type: ${{ env.BUILD_TYPE }}
          cpm-modules: ${{ github.workspace }}/build/cpm_modules

      - name: Install Qt for Linux (x64)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: linux
          target: desktop
          arch: linux_gcc_64
          dir: ${{ runner.temp }}
          modules: qtcharts qtlocation qtpositioning qtspeech qt5compat qtmultimedia qtserialport qtimageformats qtshadertools qtconnectivity qtquick3d qtsensors
          cache: true

      # - name: Build GStreamer
      #   uses: ./.github/actions/gstreamer

      - name: Configure
        working-directory: ${{ github.workspace }}
        env:
          CMAKE_PREFIX_PATH: ${{ env.QT_ROOT_DIR }}
        run: cmake -B ./build -G Ninja
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
              -DQGC_BUILD_TESTING=${{ github.event_name == 'pull_request' && 'ON' || 'OFF' }}
              -DQGC_STABLE_BUILD=${{ github.ref_type == 'tag' || contains(github.ref, 'Stable') && 'ON' || 'OFF' }}

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build ./build --target all --config ${{ env.BUILD_TYPE }}

      - name: Create AppImage
        working-directory: ${{ github.workspace }}/build
        run: cmake --install . --config ${{ env.BUILD_TYPE }}

      - name: Run unit tests
        if: github.event_name == 'pull_request'
        working-directory: ${{ github.workspace }}/build
        run: xvfb-run -a ./${{ env.ARTIFACT }} --unittest

      - name: Sanity check release excecutable
        if: github.event_name != 'pull_request'
        working-directory: ${{ github.workspace }}/build
        run: xvfb-run -a ./${{ env.ARTIFACT }} --simple-boot-test

      - name: Upload Build File
        uses: ./.github/actions/upload
        with:
          artifact_name: ${{ env.ARTIFACT }}
          package_name: ${{ env.PACKAGE }}-${{ env.BUILD_TYPE }}
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
